### ISSUE TITLE
Tasks for two separate hosts are duplicated

### ISSUE THREAD

**Issue by KeithMyers** [efmer/boinctasks-js#101]
New user is missing tasks from one host because both hosts show duplicates of the same tasks from one host.

[[url=https://flic.kr/p/2oqcLby][img]https://live.staticflickr.com/65535/52782432204_a66be938da_c.jpg[/img][/url][url=https://flic.kr/p/2oqcLby]Screenshot from 2023-03-30 17-15-35[/url] by [url=https://www.flickr.com/photos/189405854@N02/]George Generke[/url], on Flickr](url)

**Comment by efmer** [comment]
If you use the Snap store, try updating the app to 1.33 that's now the latest version, over time that should happen automatically.

I see that both have the same IP address. The local IP address is not allowed for remote access.
The local machine should be called localhost and the remote machine should have an IP address, but not 127.0.1.0 because that's the internal IP of the local machine.

So you expect the same tasks pop up twice if you use the same IP address

**Comment by George396** [comment]
Well, I've got BT working on both computers and it is showing me what I have going on in each computer, but not the other.

I stopped there because I don't know enough about how to get the 'other' computer ID'd to have it show up on what I'll call my daily driver, the 5950X machine.

The two computers have the same Password, CPID (according BOINCstats), IP address and External IP address.

Reading through AGAIN the  https://efmer.com/boinctasks-js/boinctasks-js-find-computers/  webpage:

 

The password file

The BOINC Client uses a password that is stored in a text file called <gui_rpc_auth.cfg>

     I did this and verified it three times.

 

The remote access file

Another file controls the IP addresses that are allowed to connect to BOINC client.
This text file is called <remote_hosts.cfg>. Every line may contain an IP address.

     This file itself is not in my 5950X computer, but it is within another document in my 5950X computer.


If you can’t connect, or you have a dynamic IP address, use:
<allow_remote_gui_rpc>1</allow_remote_gui_rpc> in the BOINC cc_config.xml file.

     I did this on the remote computer, GWG-PC2.

     I have removed it from the local host, GWG-PC3 (the 5950X computer).


In this case you don’t need to add anything to remote_hosts.cfg, but you do need to restart the BOINC client, see next chapter.

     I restart the BOINC client every time I make a change in BoincTasks Js.

 

For changes to have effect

Changing the files above has no effect, you MUST restart the BOINC client on every computer you make changes.

     Yes, it is done this way.

 

Adding computers manually

Computers -> Add allows you to manually add any number of undefined computers.
Next step is Computers -> Edit to change the computer name and IP address.
Make sure to activate the computer by setting the check and press Update changes.

     I stopped here to make sure what I am doing is correct.

 

Add computers automatically

With Computers-> Find most computers running BOINC can be added quicker
Make sure to type the BOINC access password and press Start.
Check the computers you want to add and press Add selected computers.

After adding computers go to Computers->Edit to modify computer names.
For computers to show up they must be activated by setting the check in front of the line.
When the edit is complete click on Update changes icon in the footer.

Cpic  (?????)

The Cpid is the BOINC identifier, that in the future will be used to connect to dynamic IP addresses.

     I’m sure this is a typo, or if not – I’m just a bit confused.

 

As a point of interest, yesterday after I deleted/removed BT from both machines per command Keith gave me, I went back into settings and checked if BT was in the apps.  IT WAS!  I then deleted v1.27.  I don't remember exactly what I did next, but also, I have rebooted both computers since.

 

On:  https://efmer.com/boinctasks/boinctasks-connect-to-linux-machine/

Checking GPU usage:

Click on “Ubuntu software” and search for ‘psensor‘ if the usage is less then 100% you may consider running multiple BOINC clients.

      I did install 'psensor' and it is running at 95% MAX.


OpenCL:

Only needed if you use a GPU, not needed to connect.

     Yes, I do have a GPU, an EVGA RTX 3080-Ti FTW3 Ultra.


The OpenCL interface might not be installed, do so with ‘sudo apt install ocl-icd-libopencl1’

     It was installed already.


For Ubuntu Only:
Make sure the GPU drivers are installed: ‘sudo ubuntu-drivers autoinstall’

     I am running 22.04 LTS and I have NVIDIA 525.89.02 installed.  Do I need to install ubuntu-drivers too?


So this is where I'm at.  I'm not sure where to go from here.

**Comment by KeithMyers** [comment]
> Well, I've got BT working on both computers and it is showing me what I have going on in each computer, but not the other.

George, that is EXACTLY what BT is SUPPOSED to do. From a single location, with only a SINGLE copy of BoincTasks running, it shows you the status of all BOINC installations, apps and tasks running on your network.

You can see all the task running on your two hosts from the single location.  Congratulations, you finally have properly installed BoincTasks.

Ignore all the rest of the "helpful" NOT information about Psensors or OpenCL or Nvidia drivers.  None of that has ANYTHING to do with successfully installing and running BoincTask.js.

**Comment by KeithMyers** [comment]
OK, I just reread your post.  Have you installed TWO copies of BT again when I specifically told you NOT to do that?

**Comment by George396** [comment]
I now have it working due to Keith Myers and his incite into reading the BT.Js webpages more than me.
Thanks anyway!
George

**Comment by KeithMyers** [comment]
Still would like the BoincTaks.js help pages to be updated and cleared out any of the superfluous commentary outside of explictly installing the BT client. This page in reference https://efmer.com/boinctasks/boinctasks-connect-to-linux-machine/[](url)
This issue can be closed in my opinion.

**Comment by efmer** [comment]
Move the GPU setting to a seperate page.
https://efmer.com/boinctasks/boinctasks-connect-to-linux-machine/
https://efmer.com/boinctasks/boinctasks-linux_gpu/
